export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const FETCH_INSTRUCTIONS_REQUEST = 'FETCH_INSTRUCTIONS_REQUEST';
export const FETCH_INSTRUCTIONS_SUCCESS = 'FETCH_INSTRUCTIONS_SUCCESS';
export const FETCH_INSTRUCTIONS_ERROR = 'FETCH_INSTRUCTIONS_ERROR';
export const TOGGLE_INSTRUCTIONS_VISIBILITY = 'TOGGLE_INSTRUCTIONS_VISIBILITY';
export const FETCH_WELCOME_MESSAGE_REQUEST = 'FETCH_WELCOME_MESSAGE_REQUEST';
export const FETCH_WELCOME_MESSAGE_SUCCESS = 'FETCH_WELCOME_MESSAGE_SUCCESS';
export const FETCH_WELCOME_MESSAGE_ERROR = 'FETCH_WELCOME_MESSAGE_ERROR';
export const TOGGLE_WELCOME_MESSAGE_VISIBILITY =
  'TOGGLE_WELCOME_MESSAGE_VISIBILITY';
